# Generated by Django 4.2.4 on 2023-08-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calification',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Calificacion'),
        ),
    ]
